### ISSUE TITLE
Resize images that are uploaded to a reasonable size.

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#124]
This issue may be related to https://github.com/Tour-de-Force/btc-app/issues/91 It appears that the image file is not resized before or after being uploaded. If I upload an image taken from my phone it could be up to or exceed 7mb. This causes the upload process to be slow and the rendering of the photo in the app also to be slow. 

We should probably resize images over 1000px on their longest edge to be 1000px. I'm not sure if we could do this within the app before uploading or if we would need to do this on the server side once the image has been uploaded. 

This will be necessary for storing many images in the future without using excessive storage space or bandwidth.

**Comment by Wally-Werner** [comment]
Decided in the meeting to do the following:
1) resize to 625 px wide by a proportional height on the client side. (the height is currently 335 px on an ipad)  (This seems like an odd size - not sure why this size was selected, maybe to have a border on narrow screens?)
2) Store the resulting image in the Couch database.
3) Store the image's dimensions (width and height) in the Couch database so that when the image is displayed, the width and height can be specified.
4) Do not replicate the images (record attachments) when the data is replicated from the server to the local database
5) When the service data is displayed, show the image by using the URL from the server-side couch database, along with the image's width and height from the local database
6) If the user is not online, display a text message in place of the image that says "app is not online now" or something to indicate that there is an image available but it can't be displayed.
7) If the user is either online or offline, and there is no image available, somehow indicate that. Right now there is a big space where the image would be, but it would be great if there was something other than a big grey block.

**Comment by samfalconer** [comment]
https://github.com/Tour-de-Force/btc-app/issues/157 is one part of this.

**Comment by samfalconer** [comment]
PR #168 covers everything but the placeholder stuff

**Comment by samfalconer** [comment]
Approved by Jeremy in PR. Merged. Closing.
