### ISSUE TITLE
Documentation on rendering vector map from database

### ISSUE THREAD

**Issue by jsieber-aca** [Tour-de-Force/btc-app#222]
Documentation describing the process used to populate a Postgres database running on Amazon RDS and using it to render the map using vector map tiles. 

This should cover the following:

1. How the existing setup works. What is needed to make the app use the vector maps delivered from the Postgres database?

2. How can we then use this to also deliver offline map capabilities?

3. What remaining issues do we have with map styling? How can we show USBRS layers, other bicycling related layers?

**Comment by jsieber-aca** [comment]
Is this where you found the OSM vector tiles?
https://openmaptiles.org/

**Comment by samfalconer** [comment]
No, but that looks like a much better option.

I was using https://github.com/rurseekatze/node-tileserver

1. The existing setup uses that application running on the tile-server-manual EC2 instance running RHEL 7. It pulls Open Street Map data stored in a Postges RDS instance downloaded from http://planet.openstreetmap.org (or another source that can provide a slice of the Earth).

To make BTC grab that data as a raster image, all that needs to be done is to change the link to opencyclemap to be your tile server. To upgrade to vector would require making it pull the JSON representation instead of the PNG and Leaflet (the client map renderer) would probably need the mapcss files to know how to render the tiles.

2. Offline was not investigated, but you could probably use the mbtiles format investigated by last year's team to package the routes.

3. You would have to define your own style using the mapcss. This is where you define the style of everything on the map. The node-tileserver that I was using also required defining what layers would be served at all at each zoom level. OpenStreetMap includes a ton of data (include the all the bicycle related information served by OpenCycleMap). It is just a matter of serving the layers you want to display and styling them the way you want.

**Comment by samfalconer** [comment]
Closing as answered and linking from the readme.
