### ISSUE TITLE
Indefinite white screen on launch (Android)

### ISSUE THREAD

**Issue by Jeremy-Friedman** [Tour-de-Force/btc-app#4]
Steps:
1) Follow README build instructions to run app on phone
2) Wait for app to launch
OR
1) Once installed, launch app directly from phone

Result:
White screen appears, indefinitely. 

Config:
Android 4.1.2

Debug notes:
Running an "adb logcat" as soon as the app launches reveals the following:
"Uncaught TypeError: Object function Object() { [native code] } has no method 'assign' at file://android_asset/www/bundle.js:171530"

The file mentioned above is in btc/www

**Comment by samfalconer** [comment]
I haven't seen this in my simulator. I think it's OS version or hardware specific.

**Comment by samfalconer** [comment]
I believe @asmasattar looked into this and the Android SDK on Jeremy's phone should theoretically be supported.

**Comment by samfalconer** [comment]
Ok, I just got an iOS build running (because it turned out to be easy), and I ran into this issue myself.

I see no one is assigned at this time and this seems to be our biggest blocker for "app not working" bugs so I'm going to take it.

I noticed 2 things on iOS:
1) If I background the app and re-open, it seems to launch quickly
2) Some of the time (maybe every time) I do this, none of the images load in the web view

**Comment by samfalconer** [comment]
Merged
